### PR TITLE
Updated to revision 5800 to fix the crash in single player mode

### PR DESCRIPTION
**Pull request by alienarena**

### CODE REVIEW

**Comment by alienarena** [comment]
bot, build

**Comment by alienarena** [comment]
@AsciiWolf there is no space available on the build server, do you know what to do?

**Comment by AsciiWolf** [comment]
bot, build

**Comment by alienarena** [comment]
Still same issue: "Error writing to file descriptor: No space left on device"

**Comment by AsciiWolf** [comment]
Well, then we sadly have to wait a little longer.

**Comment by alienarena** [comment]
bot, build

**Comment by AsciiWolf** [comment]
Try waiting a day or two. Then re-run the build.

**Comment by bbhtt** [comment]
Looking into this, probably the repo sever ran out of space while extracting the package.

**Comment by alienarena** [comment]
bot, build

**Comment by alienarena** [comment]
bot, build

**Comment by bbhtt** [comment]
starting a build every hour won't automaitcally fix things, please wait.

**Comment by alienarena** [comment]
@bbhtt it's quite a serious bug and I found the solution today, now I'm really eager to get it live. But the build process is blocking it.
Is there anyone who can clean it up manually?

**Comment by bbhtt** [comment]
I already merged a potential fix for this in linter. But it needs to be updated in the repo server. I contacted the person who can do that already.

**Comment by bbhtt** [comment]
The problem is the repo server is probably low on space and this app is too large to extract and run the linter on it.

**Comment by bbhtt** [comment]
I will merge it, if I get a working build.

**Pull request merged**
