### PR TITLE
Update the runtime

### LINKED ISSUE #16: Update the runtime
Consider updating the runtime used by this Flatpak to 23.08.

### PR DESCRIPTION
**Pull request by AsciiWolf**
Closes #16.

/cc @alienarena

### CODE REVIEW

**Comment by AsciiWolf** [comment]
Tested and works without issues:




/cc @bbhtt

**Comment by bbhtt** [comment]
Not sure why you pinged me? Is the maintainer inactive?

**Comment by AsciiWolf** [comment]
I may be mistaken, but I thought that you have push rights to most game-related repositories. Yeah, the original maintainer does not seem to be much active.

**Comment by bbhtt** [comment]
I have push access to every repo in the flathub org :)

If that's the case I'll test and merge later if the maintainer does not respond.

**Comment by AsciiWolf** [comment]
Thanks!

**Comment by alienarena** [comment]
Thanks a lot!

**Pull request merged**
